import Mathlib

set_option maxHeartbeats 800000
set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# P3 Enriched Route Language — Realization-Family Candidate Exactification

## Overview
We formalize the realization-family route language candidate and prove:
1. The forbidden descent/coarsening square commutes when both descended maps exist.
2. A finite positive model witnesses nontrivial P3 (route disagreement, not undefinedness).
3. The P1/P3 boundary is preserved: the witness is not P1 because both routes are defined.
-/

noncomputable section

/-! ## 1. Core Definitions -/

/-- A refinement system: a set P with a family of equivalence relations indexed by stages,
    where finer stages refine coarser ones. -/
structure RefinementSystem where
  /-- The process soup. -/
  P : Type
  /-- The stage index type, with a refinement partial order (≤ means "is refined by or equal"). -/
  Stage : Type
  /-- Partial order on stages: j ≤ k means k refines j (k is finer). -/
  stage_le : Stage → Stage → Prop
  /-- Equivalence relation at each stage. -/
  equiv : Stage → P → P → Prop
  /-- Each stage equivalence is reflexive. -/
  equiv_refl : ∀ (j : Stage) (x : P), equiv j x x
  /-- Each stage equivalence is symmetric. -/
  equiv_symm : ∀ (j : Stage) (x y : P), equiv j x y → equiv j y x
  /-- Each stage equivalence is transitive. -/
  equiv_trans : ∀ (j : Stage) (x y z : P), equiv j x y → equiv j y z → equiv j x z
  /-- Refinement: if k refines j, then k-equivalence implies j-equivalence. -/
  refine : ∀ (j k : Stage), stage_le j k → ∀ (x y : P), equiv k x y → equiv j x y

/-- The quotient at stage j. We use the Setoid/Quotient machinery. -/
def RefinementSystem.setoidAt (R : RefinementSystem) (j : R.Stage) : Setoid R.P where
  r := R.equiv j
  iseqv := ⟨R.equiv_refl j, R.equiv_symm j _ _, R.equiv_trans j _ _ _⟩

/-- Quotient object Q_j = P / ~_j. -/
def RefinementSystem.Q (R : RefinementSystem) (j : R.Stage) : Type :=
  Quotient (R.setoidAt j)

/-- The quotient (packaging) map Π_j : P → Q_j. -/
def RefinementSystem.packagingMap (R : RefinementSystem) (j : R.Stage) : R.P → R.Q j :=
  Quotient.mk (R.setoidAt j)

/-- Coarsening map ρ_{k→j} : Q_k → Q_j, defined when k refines j. -/
def RefinementSystem.coarsen (R : RefinementSystem) (j k : R.Stage) (hkj : R.stage_le j k) :
    R.Q k → R.Q j :=
  Quotient.lift (R.packagingMap j) (fun a b hab => Quotient.sound (R.refine j k hkj a b hab))

/-- Descent predicate: F descends at stage j iff F preserves ~_j. -/
def RefinementSystem.Descends (R : RefinementSystem) (F : R.P → R.P) (j : R.Stage) : Prop :=
  ∀ (x y : R.P), R.equiv j x y → R.equiv j (F x) (F y)

/-- Descended map F#_j : Q_j → Q_j, defined when F descends at j. -/
def RefinementSystem.descendedMap (R : RefinementSystem) (F : R.P → R.P) (j : R.Stage)
    (hd : R.Descends F j) : R.Q j → R.Q j :=
  Quotient.lift (fun x => R.packagingMap j (F x))
    (fun a b hab => Quotient.sound (hd a b hab))

/-- Route type: generated by identity, coarsening, and descended-map constructors. -/
inductive Route (R : RefinementSystem) : R.Stage → R.Stage → Type where
  | id (j : R.Stage) : Route R j j
  | coarsen (j k : R.Stage) (h : R.stage_le j k) : Route R k j
  | descended (j : R.Stage) (F : R.P → R.P) (hd : R.Descends F j) : Route R j j

/-- Route evaluation. -/
def Route.eval {R : RefinementSystem} : {s t : R.Stage} → Route R s t → R.Q s → R.Q t
  | _, _, Route.id _ => fun q => q
  | _, _, Route.coarsen j k h => R.coarsen j k h
  | _, _, Route.descended j F hd => R.descendedMap F j hd

/-- Realization family: all updates in U that descend at j and induce a given macro map M. -/
def RealizationFamily (R : RefinementSystem) (U : Set (R.P → R.P))
    (j : R.Stage) (M : R.Q j → R.Q j) : Set (R.P → R.P) :=
  { F ∈ U | ∃ (hd : R.Descends F j), R.descendedMap F j hd = M }

/-- A P3 witness: two updates from U that agree at coarse stage j but disagree at fine stage k. -/
structure P3Witness (R : RefinementSystem) (U : Set (R.P → R.P)) where
  j : R.Stage
  k : R.Stage
  hkj : R.stage_le j k
  F : R.P → R.P
  G : R.P → R.P
  hFU : F ∈ U
  hGU : G ∈ U
  hFdj : R.Descends F j
  hGdj : R.Descends G j
  hFdk : R.Descends F k
  hGdk : R.Descends G k
  agree_coarse : R.descendedMap F j hFdj = R.descendedMap G j hGdj
  witness_class : R.Q k
  disagree_fine : R.descendedMap F k hFdk witness_class ≠ R.descendedMap G k hGdk witness_class

/-! ## 2. Forbidden-Square Theorem

For a single update F that descends at both j and k (k finer than j), the square

    Q_k --F#_k--> Q_k
     |              |
    ρ_{k→j}       ρ_{k→j}
     |              |
     v              v
    Q_j --F#_j--> Q_j

commutes: ρ_{k→j} ∘ F#_k = F#_j ∘ ρ_{k→j}.
-/

theorem forbidden_square_commutes (R : RefinementSystem)
    (j k : R.Stage) (hkj : R.stage_le j k)
    (F : R.P → R.P) (hdj : R.Descends F j) (hdk : R.Descends F k) :
    ∀ (q : R.Q k),
      R.coarsen j k hkj (R.descendedMap F k hdk q) =
      R.descendedMap F j hdj (R.coarsen j k hkj q) := by
  intro q
  induction' q using Quotient.ind with x;
  rfl

/-! ## 3. Positive Finite Model

We construct a concrete model with P = Fin 4, two stages (coarse and fine),
two updates F = id and G = swap-within-coarse-classes, witnessing nontrivial P3.

Coarse stage: classes {0,1} and {2,3}.
Fine stage: discrete (each element is its own class).
F = identity, G = (0↔1, 2↔3).

- Both descend at coarse stage, with identical descended maps (both = id on Q_coarse).
- Both descend at fine stage (trivially, since fine is discrete).
- F#_fine(0) = 0 ≠ 1 = G#_fine(0): disagreement.
-/

/-- The concrete refinement system for the finite model. -/
def finiteModel : RefinementSystem where
  P := Fin 4
  Stage := Fin 2  -- 0 = coarse, 1 = fine
  stage_le := (· ≤ ·)
  equiv := fun j x y =>
    match j with
    | ⟨0, _⟩ => (x.val / 2 = y.val / 2)  -- coarse: {0,1},{2,3}
    | ⟨1, _⟩ => x = y                      -- fine: discrete
  equiv_refl := by intro j x; fin_cases j <;> simp
  equiv_symm := by intro j x y h; fin_cases j <;> simp_all
  equiv_trans := by intro j x y z h1 h2; fin_cases j <;> simp_all
  refine := by
    intro j k hjk x y hk
    fin_cases j <;> fin_cases k <;> simp_all

/-- The swap update G: 0↔1, 2↔3. -/
def swapUpdate : Fin 4 → Fin 4
  | ⟨0, _⟩ => ⟨1, by omega⟩
  | ⟨1, _⟩ => ⟨0, by omega⟩
  | ⟨2, _⟩ => ⟨3, by omega⟩
  | ⟨3, _⟩ => ⟨2, by omega⟩

/-- The update family U = {id, swapUpdate}. -/
def modelU : Set (Fin 4 → Fin 4) := {id, swapUpdate}

/-
id descends at the coarse stage (stage 0).
-/
lemma id_descends_coarse : finiteModel.Descends id ⟨0, by omega⟩ := by
  exact fun x y h => h

/-
swapUpdate descends at the coarse stage (stage 0).
-/
lemma swap_descends_coarse : finiteModel.Descends swapUpdate ⟨0, by omega⟩ := by
  unfold RefinementSystem.Descends; simp +decide [ finiteModel ] ;

/-
id descends at the fine stage (stage 1).
-/
lemma id_descends_fine : finiteModel.Descends id ⟨1, by omega⟩ := by
  exact fun x y h => h

/-
swapUpdate descends at the fine stage (stage 1).
-/
lemma swap_descends_fine : finiteModel.Descends swapUpdate ⟨1, by omega⟩ := by
  -- Since swapUpdate is injective, if swapUpdate x = swapUpdate y, then x = y.
  simp +decide [finiteModel];
  exact fun x y h => by fin_cases x <;> fin_cases y <;> trivial;

/-
The descended maps of id and swapUpdate agree at the coarse stage.
-/
lemma agree_at_coarse :
    finiteModel.descendedMap id ⟨0, by omega⟩ id_descends_coarse =
    finiteModel.descendedMap swapUpdate ⟨0, by omega⟩ swap_descends_coarse := by
  unfold finiteModel id_descends_coarse swap_descends_coarse
  generalize_proofs at *;
  ext x;
  induction x using Quotient.inductionOn';
  erw [ Quotient.eq ];
  rename_i x; fin_cases x <;> trivial;

/-
The descended maps of id and swapUpdate disagree at the fine stage on [0].
-/
lemma disagree_at_fine :
    finiteModel.descendedMap id ⟨1, by omega⟩ id_descends_fine
      (finiteModel.packagingMap ⟨1, by omega⟩ ⟨0, by omega⟩) ≠
    finiteModel.descendedMap swapUpdate ⟨1, by omega⟩ swap_descends_fine
      (finiteModel.packagingMap ⟨1, by omega⟩ ⟨0, by omega⟩) := by
  simp +decide [ finiteModel, RefinementSystem.packagingMap ];
  erw [ Quotient.eq ] ; simp +decide

/-- The P3 witness for the finite model. -/
def finiteP3Witness : P3Witness finiteModel modelU where
  j := ⟨0, by omega⟩
  k := ⟨1, by omega⟩
  hkj := by simp [finiteModel]
  F := id
  G := swapUpdate
  hFU := Or.inl rfl
  hGU := Or.inr rfl
  hFdj := id_descends_coarse
  hGdj := swap_descends_coarse
  hFdk := id_descends_fine
  hGdk := swap_descends_fine
  agree_coarse := agree_at_coarse
  witness_class := finiteModel.packagingMap ⟨1, by omega⟩ ⟨0, by omega⟩
  disagree_fine := disagree_at_fine

/-! ## 4. P1/P3 Boundary Theorem

The witness is not P1 because P1 is failure of descent (a single update failing to preserve
an equivalence relation at a stage). In the P3 witness, both F and G descend at the fine stage k.
The disagreement is between two *defined* descended maps, not from any route being undefined.
-/

/-- Both updates in the P3 witness descend at the fine stage: the witness is not P1. -/
theorem p3_witness_not_p1 :
    finiteModel.Descends finiteP3Witness.F finiteP3Witness.k ∧
    finiteModel.Descends finiteP3Witness.G finiteP3Witness.k :=
  ⟨finiteP3Witness.hFdk, finiteP3Witness.hGdk⟩

/-! ## 5. Forbidden Square is Distinct from Witness

The forbidden square involves a *single* update and tests commutativity of
ρ ∘ F#_k vs F#_j ∘ ρ. The P3 witness involves *two* updates and tests
F#_k vs G#_k (same source, same target, same stage). These are structurally distinct.
-/

end